spring.application.name=marmura_order_manager
spring.datasource.url=jdbc:mysql://localhost:3306/marble_orders
spring.datasource.username=mario
spring.datasource.password=mario
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081